name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{DOCKER_USERNAME}}
        password: ${{DOCKER_PASSWORD}}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./rest-with-spring-boot-and-java\05_FirstStepsInJavaWithSpringBoot
      run: mvn -clean package

    - name: Docker compose build
      working-directory: ./rest-with-spring-boot-and-java
      run: docker compose build
